[package]
name = "sysbadge-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysbadge-usb = { path = "../usb" }

druid = { version = "0.8.3", features = ["im"] }
