[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C", "linker=flip-link",
    #"-C", "link-arg=--nmagic",
    #"-C", "link-arg=-Tlink.x",
    #"-C", "link-arg=-Tdefmt.x",

    "-Z", "trap-unreachable=no",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]
# Choose a default "cargo run" tool:
# - probe-run provides flashing and defmt via a hardware debugger, and stack unwind on panic
# - elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode
# - "probe-rs run" is similar to probe-run but it uses the latest probe-rs lib crate
# runner = "probe-run --chip RP2040"
# runner = "elf2uf2-rs -d"
# runner = "probe-rs run --chip RP2040 --protocol swd"
runner = "probe-run --chip nRF52840_xxAA"

[target.'cfg(not(all(target_arch = "arm", target_os = "none")))']
rustflags = [
    #"-C", "linker=flip-link",
    #"-C", "link-arg=--nmagic",
    #"-C", "link-arg=-Tlink.x",
    #"-C", "link-arg=-Tdefmt.x",

    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[unstable]
#build-std = [ "compiler_builtins", "core", "alloc", "std" ]

[env]
DEFMT_LOG = "debug"
SYSBADGE_WEB = "https://sysbadge.kloenk.eu"
SYSBADGE_MATRIX = "@kloenk:kloenk.eu"
