name: "Web deployment"

on:
  push:
    branches:
    - main

jobs:
  nix:
    uses: ./.github/workflows/nix.yml
  deploy:
    name: "Deploy web"
    needs: [ nix ]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Download build web directory
      id: download
      uses: actions/download-artifact@v3
      with:
        name: web
        path: dist/
    - name: Download build web directory
      id: download-fw
      uses: actions/download-artifact@v3
      with:
        name: firmware
        path: dist/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/
        clean-exclude: pr-preview/