name: "Pull Request queue"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  nix:
    uses: ./.github/workflows/nix.yml
  deploy-preview:
    name: "Deploy preview web"
    needs: [ nix ]
    concurrency: preview-${{ github.ref }}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Download build web directory
        id: download
        uses: actions/download-artifact@v3
        with:
          name: web
          path: dist/
      - name: Download build web directory
        id: download-fw
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: dist/
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist/
